apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: game
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      imagePullSecrets: [{ name: ghcr-cred }]
      containers:
        - name: api
          image: ghcr.io/andrew-all-proj/game-api:test
          imagePullPolicy: Always
          ports: [{ containerPort: 3000, name: http }]
          envFrom:
            - secretRef: { name: api-env }
          volumeMounts:
            - { name: uploads, mountPath: /app/uploads }
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: uploads
          persistentVolumeClaim: { claimName: uploads }
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: game
spec:
  selector: { app: api }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
